name = "delete-old-deployment"
main = "./Target/Index.js"
compatibility_date = "2023-05-18"
compatibility_flags = ["nodejs_compat"]
keep_vars = true
send_metrics = true
tsconfig = "./tsconfig.json"
workers_dev = false

[build]
command = "npm run prepublishOnly"
cwd = "."
watch_dir = "./Source"

[dev]
ip = "127.0.0.1"
port = 4001

[placement]
mode = "smart"
